repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: checkov
        name: checkov (system)
        entry: checkov -d . --config-file .checkov.yaml
        language: system
        pass_filenames: false
        always_run: true
